// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(rebel_wallet_coreFFI)
import rebel_wallet_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_rebel_wallet_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_rebel_wallet_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureRebelWalletCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol FfiAppProtocol: AnyObject, Sendable {
    
    func dispatch(action: AppAction) 
    
    func listenForUpdates(reconciler: AppReconciler) 
    
    func state()  -> AppState
    
}
open class FfiApp: FfiAppProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_rebel_wallet_core_fn_clone_ffiapp(self.handle, $0) }
    }
public convenience init(dataDir: String, secretStore: SecretStore) {
    let handle =
        try! rustCall() {
    uniffi_rebel_wallet_core_fn_constructor_ffiapp_new(
        FfiConverterString.lower(dataDir),
        FfiConverterCallbackInterfaceSecretStore_lower(secretStore),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_rebel_wallet_core_fn_free_ffiapp(handle, $0) }
    }

    

    
open func dispatch(action: AppAction)  {try! rustCall() {
    uniffi_rebel_wallet_core_fn_method_ffiapp_dispatch(
            self.uniffiCloneHandle(),
        FfiConverterTypeAppAction_lower(action),$0
    )
}
}
    
open func listenForUpdates(reconciler: AppReconciler)  {try! rustCall() {
    uniffi_rebel_wallet_core_fn_method_ffiapp_listen_for_updates(
            self.uniffiCloneHandle(),
        FfiConverterCallbackInterfaceAppReconciler_lower(reconciler),$0
    )
}
}
    
open func state() -> AppState  {
    return try!  FfiConverterTypeAppState_lift(try! rustCall() {
    uniffi_rebel_wallet_core_fn_method_ffiapp_state(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiApp: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = FfiApp

    public static func lift(_ handle: UInt64) throws -> FfiApp {
        return FfiApp(unsafeFromHandle: handle)
    }

    public static func lower(_ value: FfiApp) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiApp {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: FfiApp, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiApp_lift(_ handle: UInt64) throws -> FfiApp {
    return try FfiConverterTypeFfiApp.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiApp_lower(_ value: FfiApp) -> UInt64 {
    return FfiConverterTypeFfiApp.lower(value)
}




public struct ActivityItem: Equatable, Hashable {
    public var id: String
    public var title: String
    public var subtitle: String
    public var amountSat: Int64
    public var status: String
    public var timestamp: String
    public var counterpartyName: String
    public var counterpartyPicture: String
    public var counterpartyKnown: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, title: String, subtitle: String, amountSat: Int64, status: String, timestamp: String, counterpartyName: String, counterpartyPicture: String, counterpartyKnown: Bool) {
        self.id = id
        self.title = title
        self.subtitle = subtitle
        self.amountSat = amountSat
        self.status = status
        self.timestamp = timestamp
        self.counterpartyName = counterpartyName
        self.counterpartyPicture = counterpartyPicture
        self.counterpartyKnown = counterpartyKnown
    }

    

    
}

#if compiler(>=6)
extension ActivityItem: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeActivityItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ActivityItem {
        return
            try ActivityItem(
                id: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                subtitle: FfiConverterString.read(from: &buf), 
                amountSat: FfiConverterInt64.read(from: &buf), 
                status: FfiConverterString.read(from: &buf), 
                timestamp: FfiConverterString.read(from: &buf), 
                counterpartyName: FfiConverterString.read(from: &buf), 
                counterpartyPicture: FfiConverterString.read(from: &buf), 
                counterpartyKnown: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: ActivityItem, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.subtitle, into: &buf)
        FfiConverterInt64.write(value.amountSat, into: &buf)
        FfiConverterString.write(value.status, into: &buf)
        FfiConverterString.write(value.timestamp, into: &buf)
        FfiConverterString.write(value.counterpartyName, into: &buf)
        FfiConverterString.write(value.counterpartyPicture, into: &buf)
        FfiConverterBool.write(value.counterpartyKnown, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeActivityItem_lift(_ buf: RustBuffer) throws -> ActivityItem {
    return try FfiConverterTypeActivityItem.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeActivityItem_lower(_ value: ActivityItem) -> RustBuffer {
    return FfiConverterTypeActivityItem.lower(value)
}


public struct AppState: Equatable, Hashable {
    public var rev: UInt64
    public var router: Router
    public var setup: SetupState
    public var wallet: WalletState
    public var receive: ReceiveState
    public var send: SendState
    public var nostr: NostrState
    public var directMessages: [NostrMessage]
    public var activity: [ActivityItem]
    public var recoveryPhrase: String?
    public var toast: String?
    public var busy: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(rev: UInt64, router: Router, setup: SetupState, wallet: WalletState, receive: ReceiveState, send: SendState, nostr: NostrState, directMessages: [NostrMessage], activity: [ActivityItem], recoveryPhrase: String?, toast: String?, busy: Bool) {
        self.rev = rev
        self.router = router
        self.setup = setup
        self.wallet = wallet
        self.receive = receive
        self.send = send
        self.nostr = nostr
        self.directMessages = directMessages
        self.activity = activity
        self.recoveryPhrase = recoveryPhrase
        self.toast = toast
        self.busy = busy
    }

    

    
}

#if compiler(>=6)
extension AppState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAppState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AppState {
        return
            try AppState(
                rev: FfiConverterUInt64.read(from: &buf), 
                router: FfiConverterTypeRouter.read(from: &buf), 
                setup: FfiConverterTypeSetupState.read(from: &buf), 
                wallet: FfiConverterTypeWalletState.read(from: &buf), 
                receive: FfiConverterTypeReceiveState.read(from: &buf), 
                send: FfiConverterTypeSendState.read(from: &buf), 
                nostr: FfiConverterTypeNostrState.read(from: &buf), 
                directMessages: FfiConverterSequenceTypeNostrMessage.read(from: &buf), 
                activity: FfiConverterSequenceTypeActivityItem.read(from: &buf), 
                recoveryPhrase: FfiConverterOptionString.read(from: &buf), 
                toast: FfiConverterOptionString.read(from: &buf), 
                busy: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: AppState, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.rev, into: &buf)
        FfiConverterTypeRouter.write(value.router, into: &buf)
        FfiConverterTypeSetupState.write(value.setup, into: &buf)
        FfiConverterTypeWalletState.write(value.wallet, into: &buf)
        FfiConverterTypeReceiveState.write(value.receive, into: &buf)
        FfiConverterTypeSendState.write(value.send, into: &buf)
        FfiConverterTypeNostrState.write(value.nostr, into: &buf)
        FfiConverterSequenceTypeNostrMessage.write(value.directMessages, into: &buf)
        FfiConverterSequenceTypeActivityItem.write(value.activity, into: &buf)
        FfiConverterOptionString.write(value.recoveryPhrase, into: &buf)
        FfiConverterOptionString.write(value.toast, into: &buf)
        FfiConverterBool.write(value.busy, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAppState_lift(_ buf: RustBuffer) throws -> AppState {
    return try FfiConverterTypeAppState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAppState_lower(_ value: AppState) -> RustBuffer {
    return FfiConverterTypeAppState.lower(value)
}


public struct Contact: Equatable, Hashable {
    public var id: String
    public var npub: String
    public var name: String
    public var followed: Bool
    public var picture: String
    public var lightningAddress: String
    public var lnurl: String
    public var lastUsed: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, npub: String, name: String, followed: Bool, picture: String, lightningAddress: String, lnurl: String, lastUsed: UInt64) {
        self.id = id
        self.npub = npub
        self.name = name
        self.followed = followed
        self.picture = picture
        self.lightningAddress = lightningAddress
        self.lnurl = lnurl
        self.lastUsed = lastUsed
    }

    

    
}

#if compiler(>=6)
extension Contact: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeContact: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Contact {
        return
            try Contact(
                id: FfiConverterString.read(from: &buf), 
                npub: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                followed: FfiConverterBool.read(from: &buf), 
                picture: FfiConverterString.read(from: &buf), 
                lightningAddress: FfiConverterString.read(from: &buf), 
                lnurl: FfiConverterString.read(from: &buf), 
                lastUsed: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: Contact, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.npub, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterBool.write(value.followed, into: &buf)
        FfiConverterString.write(value.picture, into: &buf)
        FfiConverterString.write(value.lightningAddress, into: &buf)
        FfiConverterString.write(value.lnurl, into: &buf)
        FfiConverterUInt64.write(value.lastUsed, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeContact_lift(_ buf: RustBuffer) throws -> Contact {
    return try FfiConverterTypeContact.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeContact_lower(_ value: Contact) -> RustBuffer {
    return FfiConverterTypeContact.lower(value)
}


public struct NostrMessage: Equatable, Hashable {
    public var id: String
    public var contactId: String
    public var body: String
    public var inbound: Bool
    public var timestamp: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, contactId: String, body: String, inbound: Bool, timestamp: String) {
        self.id = id
        self.contactId = contactId
        self.body = body
        self.inbound = inbound
        self.timestamp = timestamp
    }

    

    
}

#if compiler(>=6)
extension NostrMessage: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNostrMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NostrMessage {
        return
            try NostrMessage(
                id: FfiConverterString.read(from: &buf), 
                contactId: FfiConverterString.read(from: &buf), 
                body: FfiConverterString.read(from: &buf), 
                inbound: FfiConverterBool.read(from: &buf), 
                timestamp: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: NostrMessage, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.contactId, into: &buf)
        FfiConverterString.write(value.body, into: &buf)
        FfiConverterBool.write(value.inbound, into: &buf)
        FfiConverterString.write(value.timestamp, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNostrMessage_lift(_ buf: RustBuffer) throws -> NostrMessage {
    return try FfiConverterTypeNostrMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNostrMessage_lower(_ value: NostrMessage) -> RustBuffer {
    return FfiConverterTypeNostrMessage.lower(value)
}


public struct NostrState: Equatable, Hashable {
    public var npub: String?
    public var name: String
    public var about: String
    public var picture: String
    public var lud16: String
    public var nip05: String
    public var contacts: [Contact]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(npub: String?, name: String, about: String, picture: String, lud16: String, nip05: String, contacts: [Contact]) {
        self.npub = npub
        self.name = name
        self.about = about
        self.picture = picture
        self.lud16 = lud16
        self.nip05 = nip05
        self.contacts = contacts
    }

    

    
}

#if compiler(>=6)
extension NostrState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNostrState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NostrState {
        return
            try NostrState(
                npub: FfiConverterOptionString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                about: FfiConverterString.read(from: &buf), 
                picture: FfiConverterString.read(from: &buf), 
                lud16: FfiConverterString.read(from: &buf), 
                nip05: FfiConverterString.read(from: &buf), 
                contacts: FfiConverterSequenceTypeContact.read(from: &buf)
        )
    }

    public static func write(_ value: NostrState, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.npub, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.about, into: &buf)
        FfiConverterString.write(value.picture, into: &buf)
        FfiConverterString.write(value.lud16, into: &buf)
        FfiConverterString.write(value.nip05, into: &buf)
        FfiConverterSequenceTypeContact.write(value.contacts, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNostrState_lift(_ buf: RustBuffer) throws -> NostrState {
    return try FfiConverterTypeNostrState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNostrState_lower(_ value: NostrState) -> RustBuffer {
    return FfiConverterTypeNostrState.lower(value)
}


public struct ReceiveState: Equatable, Hashable {
    public var arkAddress: String?
    public var lightningInvoice: String?
    public var lightningPaymentHash: String?
    public var lightningStatus: String
    public var lightningPaid: Bool
    public var amountSat: UInt64
    public var memo: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(arkAddress: String?, lightningInvoice: String?, lightningPaymentHash: String?, lightningStatus: String, lightningPaid: Bool, amountSat: UInt64, memo: String) {
        self.arkAddress = arkAddress
        self.lightningInvoice = lightningInvoice
        self.lightningPaymentHash = lightningPaymentHash
        self.lightningStatus = lightningStatus
        self.lightningPaid = lightningPaid
        self.amountSat = amountSat
        self.memo = memo
    }

    

    
}

#if compiler(>=6)
extension ReceiveState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeReceiveState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ReceiveState {
        return
            try ReceiveState(
                arkAddress: FfiConverterOptionString.read(from: &buf), 
                lightningInvoice: FfiConverterOptionString.read(from: &buf), 
                lightningPaymentHash: FfiConverterOptionString.read(from: &buf), 
                lightningStatus: FfiConverterString.read(from: &buf), 
                lightningPaid: FfiConverterBool.read(from: &buf), 
                amountSat: FfiConverterUInt64.read(from: &buf), 
                memo: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ReceiveState, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.arkAddress, into: &buf)
        FfiConverterOptionString.write(value.lightningInvoice, into: &buf)
        FfiConverterOptionString.write(value.lightningPaymentHash, into: &buf)
        FfiConverterString.write(value.lightningStatus, into: &buf)
        FfiConverterBool.write(value.lightningPaid, into: &buf)
        FfiConverterUInt64.write(value.amountSat, into: &buf)
        FfiConverterString.write(value.memo, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReceiveState_lift(_ buf: RustBuffer) throws -> ReceiveState {
    return try FfiConverterTypeReceiveState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReceiveState_lower(_ value: ReceiveState) -> RustBuffer {
    return FfiConverterTypeReceiveState.lower(value)
}


public struct Router: Equatable, Hashable {
    public var defaultScreen: Screen
    public var screenStack: [Screen]
    public var selectedTab: MainTab

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(defaultScreen: Screen, screenStack: [Screen], selectedTab: MainTab) {
        self.defaultScreen = defaultScreen
        self.screenStack = screenStack
        self.selectedTab = selectedTab
    }

    

    
}

#if compiler(>=6)
extension Router: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRouter: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Router {
        return
            try Router(
                defaultScreen: FfiConverterTypeScreen.read(from: &buf), 
                screenStack: FfiConverterSequenceTypeScreen.read(from: &buf), 
                selectedTab: FfiConverterTypeMainTab.read(from: &buf)
        )
    }

    public static func write(_ value: Router, into buf: inout [UInt8]) {
        FfiConverterTypeScreen.write(value.defaultScreen, into: &buf)
        FfiConverterSequenceTypeScreen.write(value.screenStack, into: &buf)
        FfiConverterTypeMainTab.write(value.selectedTab, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRouter_lift(_ buf: RustBuffer) throws -> Router {
    return try FfiConverterTypeRouter.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRouter_lower(_ value: Router) -> RustBuffer {
    return FfiConverterTypeRouter.lower(value)
}


public struct SendState: Equatable, Hashable {
    public var destination: String
    public var amountSat: UInt64
    public var memo: String
    public var lastResult: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(destination: String, amountSat: UInt64, memo: String, lastResult: String?) {
        self.destination = destination
        self.amountSat = amountSat
        self.memo = memo
        self.lastResult = lastResult
    }

    

    
}

#if compiler(>=6)
extension SendState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSendState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SendState {
        return
            try SendState(
                destination: FfiConverterString.read(from: &buf), 
                amountSat: FfiConverterUInt64.read(from: &buf), 
                memo: FfiConverterString.read(from: &buf), 
                lastResult: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: SendState, into buf: inout [UInt8]) {
        FfiConverterString.write(value.destination, into: &buf)
        FfiConverterUInt64.write(value.amountSat, into: &buf)
        FfiConverterString.write(value.memo, into: &buf)
        FfiConverterOptionString.write(value.lastResult, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendState_lift(_ buf: RustBuffer) throws -> SendState {
    return try FfiConverterTypeSendState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSendState_lower(_ value: SendState) -> RustBuffer {
    return FfiConverterTypeSendState.lower(value)
}


public struct WalletState: Equatable, Hashable {
    public var network: String
    public var serverAddress: String
    public var balanceSat: UInt64
    public var pendingReceiveSat: UInt64
    public var pendingSendSat: UInt64
    public var lastSync: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(network: String, serverAddress: String, balanceSat: UInt64, pendingReceiveSat: UInt64, pendingSendSat: UInt64, lastSync: String?) {
        self.network = network
        self.serverAddress = serverAddress
        self.balanceSat = balanceSat
        self.pendingReceiveSat = pendingReceiveSat
        self.pendingSendSat = pendingSendSat
        self.lastSync = lastSync
    }

    

    
}

#if compiler(>=6)
extension WalletState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWalletState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WalletState {
        return
            try WalletState(
                network: FfiConverterString.read(from: &buf), 
                serverAddress: FfiConverterString.read(from: &buf), 
                balanceSat: FfiConverterUInt64.read(from: &buf), 
                pendingReceiveSat: FfiConverterUInt64.read(from: &buf), 
                pendingSendSat: FfiConverterUInt64.read(from: &buf), 
                lastSync: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: WalletState, into buf: inout [UInt8]) {
        FfiConverterString.write(value.network, into: &buf)
        FfiConverterString.write(value.serverAddress, into: &buf)
        FfiConverterUInt64.write(value.balanceSat, into: &buf)
        FfiConverterUInt64.write(value.pendingReceiveSat, into: &buf)
        FfiConverterUInt64.write(value.pendingSendSat, into: &buf)
        FfiConverterOptionString.write(value.lastSync, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalletState_lift(_ buf: RustBuffer) throws -> WalletState {
    return try FfiConverterTypeWalletState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalletState_lower(_ value: WalletState) -> RustBuffer {
    return FfiConverterTypeWalletState.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum AppAction: Equatable, Hashable {
    
    case bootstrap
    case createWallet
    case restoreWallet(mnemonic: String
    )
    case replaceWallet(mnemonic: String
    )
    case showSeed
    case syncWallet
    case selectTab(tab: MainTab
    )
    case pushScreen(screen: Screen
    )
    case popScreen
    case updateScreenStack(stack: [Screen]
    )
    case setReceiveAmount(amountSat: UInt64
    )
    case setReceiveMemo(memo: String
    )
    case createArkAddress
    case createLightningInvoice
    case setSendDestination(destination: String
    )
    case setSendAmount(amountSat: UInt64
    )
    case setSendMemo(memo: String
    )
    case payDestination
    case payLightningInvoice(invoice: String, amountSat: UInt64?
    )
    case payArkAddress(address: String, amountSat: UInt64
    )
    case generateNostrKey
    case importNostrSecret(nsecOrHex: String
    )
    case exportNostrSecret
    case clearNostrKey
    case editNostrProfile(name: String, about: String, picture: String, lud16: String, nip05: String
    )
    case uploadNostrProfilePicture(imageBase64: String
    )
    case addContact(npub: String, name: String, lightningAddress: String, lnurl: String, picture: String
    )
    case editContact(contactId: String, name: String, npub: String, lightningAddress: String, lnurl: String, picture: String
    )
    case followContact(contactId: String
    )
    case unfollowContact(contactId: String
    )
    case deleteContact(contactId: String
    )
    case publishNostrProfile
    case refreshNostrProfile
    case deleteNostrProfile
    case publishContactList
    case refreshContactList
    case loadDirectMessages(contactId: String
    )
    case sendDirectMessage(contactId: String, message: String
    )
    case clearToast





}

#if compiler(>=6)
extension AppAction: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAppAction: FfiConverterRustBuffer {
    typealias SwiftType = AppAction

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AppAction {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .bootstrap
        
        case 2: return .createWallet
        
        case 3: return .restoreWallet(mnemonic: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .replaceWallet(mnemonic: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .showSeed
        
        case 6: return .syncWallet
        
        case 7: return .selectTab(tab: try FfiConverterTypeMainTab.read(from: &buf)
        )
        
        case 8: return .pushScreen(screen: try FfiConverterTypeScreen.read(from: &buf)
        )
        
        case 9: return .popScreen
        
        case 10: return .updateScreenStack(stack: try FfiConverterSequenceTypeScreen.read(from: &buf)
        )
        
        case 11: return .setReceiveAmount(amountSat: try FfiConverterUInt64.read(from: &buf)
        )
        
        case 12: return .setReceiveMemo(memo: try FfiConverterString.read(from: &buf)
        )
        
        case 13: return .createArkAddress
        
        case 14: return .createLightningInvoice
        
        case 15: return .setSendDestination(destination: try FfiConverterString.read(from: &buf)
        )
        
        case 16: return .setSendAmount(amountSat: try FfiConverterUInt64.read(from: &buf)
        )
        
        case 17: return .setSendMemo(memo: try FfiConverterString.read(from: &buf)
        )
        
        case 18: return .payDestination
        
        case 19: return .payLightningInvoice(invoice: try FfiConverterString.read(from: &buf), amountSat: try FfiConverterOptionUInt64.read(from: &buf)
        )
        
        case 20: return .payArkAddress(address: try FfiConverterString.read(from: &buf), amountSat: try FfiConverterUInt64.read(from: &buf)
        )
        
        case 21: return .generateNostrKey
        
        case 22: return .importNostrSecret(nsecOrHex: try FfiConverterString.read(from: &buf)
        )
        
        case 23: return .exportNostrSecret
        
        case 24: return .clearNostrKey
        
        case 25: return .editNostrProfile(name: try FfiConverterString.read(from: &buf), about: try FfiConverterString.read(from: &buf), picture: try FfiConverterString.read(from: &buf), lud16: try FfiConverterString.read(from: &buf), nip05: try FfiConverterString.read(from: &buf)
        )
        
        case 26: return .uploadNostrProfilePicture(imageBase64: try FfiConverterString.read(from: &buf)
        )
        
        case 27: return .addContact(npub: try FfiConverterString.read(from: &buf), name: try FfiConverterString.read(from: &buf), lightningAddress: try FfiConverterString.read(from: &buf), lnurl: try FfiConverterString.read(from: &buf), picture: try FfiConverterString.read(from: &buf)
        )
        
        case 28: return .editContact(contactId: try FfiConverterString.read(from: &buf), name: try FfiConverterString.read(from: &buf), npub: try FfiConverterString.read(from: &buf), lightningAddress: try FfiConverterString.read(from: &buf), lnurl: try FfiConverterString.read(from: &buf), picture: try FfiConverterString.read(from: &buf)
        )
        
        case 29: return .followContact(contactId: try FfiConverterString.read(from: &buf)
        )
        
        case 30: return .unfollowContact(contactId: try FfiConverterString.read(from: &buf)
        )
        
        case 31: return .deleteContact(contactId: try FfiConverterString.read(from: &buf)
        )
        
        case 32: return .publishNostrProfile
        
        case 33: return .refreshNostrProfile
        
        case 34: return .deleteNostrProfile
        
        case 35: return .publishContactList
        
        case 36: return .refreshContactList
        
        case 37: return .loadDirectMessages(contactId: try FfiConverterString.read(from: &buf)
        )
        
        case 38: return .sendDirectMessage(contactId: try FfiConverterString.read(from: &buf), message: try FfiConverterString.read(from: &buf)
        )
        
        case 39: return .clearToast
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AppAction, into buf: inout [UInt8]) {
        switch value {
        
        
        case .bootstrap:
            writeInt(&buf, Int32(1))
        
        
        case .createWallet:
            writeInt(&buf, Int32(2))
        
        
        case let .restoreWallet(mnemonic):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(mnemonic, into: &buf)
            
        
        case let .replaceWallet(mnemonic):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(mnemonic, into: &buf)
            
        
        case .showSeed:
            writeInt(&buf, Int32(5))
        
        
        case .syncWallet:
            writeInt(&buf, Int32(6))
        
        
        case let .selectTab(tab):
            writeInt(&buf, Int32(7))
            FfiConverterTypeMainTab.write(tab, into: &buf)
            
        
        case let .pushScreen(screen):
            writeInt(&buf, Int32(8))
            FfiConverterTypeScreen.write(screen, into: &buf)
            
        
        case .popScreen:
            writeInt(&buf, Int32(9))
        
        
        case let .updateScreenStack(stack):
            writeInt(&buf, Int32(10))
            FfiConverterSequenceTypeScreen.write(stack, into: &buf)
            
        
        case let .setReceiveAmount(amountSat):
            writeInt(&buf, Int32(11))
            FfiConverterUInt64.write(amountSat, into: &buf)
            
        
        case let .setReceiveMemo(memo):
            writeInt(&buf, Int32(12))
            FfiConverterString.write(memo, into: &buf)
            
        
        case .createArkAddress:
            writeInt(&buf, Int32(13))
        
        
        case .createLightningInvoice:
            writeInt(&buf, Int32(14))
        
        
        case let .setSendDestination(destination):
            writeInt(&buf, Int32(15))
            FfiConverterString.write(destination, into: &buf)
            
        
        case let .setSendAmount(amountSat):
            writeInt(&buf, Int32(16))
            FfiConverterUInt64.write(amountSat, into: &buf)
            
        
        case let .setSendMemo(memo):
            writeInt(&buf, Int32(17))
            FfiConverterString.write(memo, into: &buf)
            
        
        case .payDestination:
            writeInt(&buf, Int32(18))
        
        
        case let .payLightningInvoice(invoice,amountSat):
            writeInt(&buf, Int32(19))
            FfiConverterString.write(invoice, into: &buf)
            FfiConverterOptionUInt64.write(amountSat, into: &buf)
            
        
        case let .payArkAddress(address,amountSat):
            writeInt(&buf, Int32(20))
            FfiConverterString.write(address, into: &buf)
            FfiConverterUInt64.write(amountSat, into: &buf)
            
        
        case .generateNostrKey:
            writeInt(&buf, Int32(21))
        
        
        case let .importNostrSecret(nsecOrHex):
            writeInt(&buf, Int32(22))
            FfiConverterString.write(nsecOrHex, into: &buf)
            
        
        case .exportNostrSecret:
            writeInt(&buf, Int32(23))
        
        
        case .clearNostrKey:
            writeInt(&buf, Int32(24))
        
        
        case let .editNostrProfile(name,about,picture,lud16,nip05):
            writeInt(&buf, Int32(25))
            FfiConverterString.write(name, into: &buf)
            FfiConverterString.write(about, into: &buf)
            FfiConverterString.write(picture, into: &buf)
            FfiConverterString.write(lud16, into: &buf)
            FfiConverterString.write(nip05, into: &buf)
            
        
        case let .uploadNostrProfilePicture(imageBase64):
            writeInt(&buf, Int32(26))
            FfiConverterString.write(imageBase64, into: &buf)
            
        
        case let .addContact(npub,name,lightningAddress,lnurl,picture):
            writeInt(&buf, Int32(27))
            FfiConverterString.write(npub, into: &buf)
            FfiConverterString.write(name, into: &buf)
            FfiConverterString.write(lightningAddress, into: &buf)
            FfiConverterString.write(lnurl, into: &buf)
            FfiConverterString.write(picture, into: &buf)
            
        
        case let .editContact(contactId,name,npub,lightningAddress,lnurl,picture):
            writeInt(&buf, Int32(28))
            FfiConverterString.write(contactId, into: &buf)
            FfiConverterString.write(name, into: &buf)
            FfiConverterString.write(npub, into: &buf)
            FfiConverterString.write(lightningAddress, into: &buf)
            FfiConverterString.write(lnurl, into: &buf)
            FfiConverterString.write(picture, into: &buf)
            
        
        case let .followContact(contactId):
            writeInt(&buf, Int32(29))
            FfiConverterString.write(contactId, into: &buf)
            
        
        case let .unfollowContact(contactId):
            writeInt(&buf, Int32(30))
            FfiConverterString.write(contactId, into: &buf)
            
        
        case let .deleteContact(contactId):
            writeInt(&buf, Int32(31))
            FfiConverterString.write(contactId, into: &buf)
            
        
        case .publishNostrProfile:
            writeInt(&buf, Int32(32))
        
        
        case .refreshNostrProfile:
            writeInt(&buf, Int32(33))
        
        
        case .deleteNostrProfile:
            writeInt(&buf, Int32(34))
        
        
        case .publishContactList:
            writeInt(&buf, Int32(35))
        
        
        case .refreshContactList:
            writeInt(&buf, Int32(36))
        
        
        case let .loadDirectMessages(contactId):
            writeInt(&buf, Int32(37))
            FfiConverterString.write(contactId, into: &buf)
            
        
        case let .sendDirectMessage(contactId,message):
            writeInt(&buf, Int32(38))
            FfiConverterString.write(contactId, into: &buf)
            FfiConverterString.write(message, into: &buf)
            
        
        case .clearToast:
            writeInt(&buf, Int32(39))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAppAction_lift(_ buf: RustBuffer) throws -> AppAction {
    return try FfiConverterTypeAppAction.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAppAction_lower(_ value: AppAction) -> RustBuffer {
    return FfiConverterTypeAppAction.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum AppUpdate: Equatable, Hashable {
    
    case fullState(AppState
    )





}

#if compiler(>=6)
extension AppUpdate: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAppUpdate: FfiConverterRustBuffer {
    typealias SwiftType = AppUpdate

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AppUpdate {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .fullState(try FfiConverterTypeAppState.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AppUpdate, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .fullState(v1):
            writeInt(&buf, Int32(1))
            FfiConverterTypeAppState.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAppUpdate_lift(_ buf: RustBuffer) throws -> AppUpdate {
    return try FfiConverterTypeAppUpdate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAppUpdate_lower(_ value: AppUpdate) -> RustBuffer {
    return FfiConverterTypeAppUpdate.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum MainTab: Equatable, Hashable {
    
    case home
    case activity
    case contacts
    case settings





}

#if compiler(>=6)
extension MainTab: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMainTab: FfiConverterRustBuffer {
    typealias SwiftType = MainTab

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MainTab {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .home
        
        case 2: return .activity
        
        case 3: return .contacts
        
        case 4: return .settings
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MainTab, into buf: inout [UInt8]) {
        switch value {
        
        
        case .home:
            writeInt(&buf, Int32(1))
        
        
        case .activity:
            writeInt(&buf, Int32(2))
        
        
        case .contacts:
            writeInt(&buf, Int32(3))
        
        
        case .settings:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMainTab_lift(_ buf: RustBuffer) throws -> MainTab {
    return try FfiConverterTypeMainTab.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMainTab_lower(_ value: MainTab) -> RustBuffer {
    return FfiConverterTypeMainTab.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Screen: Equatable, Hashable {
    
    case setup
    case home
    case send
    case receive
    case profile
    case backup
    case restore
    case contactDetail(contactId: String
    )





}

#if compiler(>=6)
extension Screen: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeScreen: FfiConverterRustBuffer {
    typealias SwiftType = Screen

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Screen {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .setup
        
        case 2: return .home
        
        case 3: return .send
        
        case 4: return .receive
        
        case 5: return .profile
        
        case 6: return .backup
        
        case 7: return .restore
        
        case 8: return .contactDetail(contactId: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Screen, into buf: inout [UInt8]) {
        switch value {
        
        
        case .setup:
            writeInt(&buf, Int32(1))
        
        
        case .home:
            writeInt(&buf, Int32(2))
        
        
        case .send:
            writeInt(&buf, Int32(3))
        
        
        case .receive:
            writeInt(&buf, Int32(4))
        
        
        case .profile:
            writeInt(&buf, Int32(5))
        
        
        case .backup:
            writeInt(&buf, Int32(6))
        
        
        case .restore:
            writeInt(&buf, Int32(7))
        
        
        case let .contactDetail(contactId):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(contactId, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScreen_lift(_ buf: RustBuffer) throws -> Screen {
    return try FfiConverterTypeScreen.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScreen_lower(_ value: Screen) -> RustBuffer {
    return FfiConverterTypeScreen.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SetupState: Equatable, Hashable {
    
    case needsSetup
    case ready
    case error(message: String
    )





}

#if compiler(>=6)
extension SetupState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSetupState: FfiConverterRustBuffer {
    typealias SwiftType = SetupState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SetupState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .needsSetup
        
        case 2: return .ready
        
        case 3: return .error(message: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SetupState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .needsSetup:
            writeInt(&buf, Int32(1))
        
        
        case .ready:
            writeInt(&buf, Int32(2))
        
        
        case let .error(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSetupState_lift(_ buf: RustBuffer) throws -> SetupState {
    return try FfiConverterTypeSetupState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSetupState_lower(_ value: SetupState) -> RustBuffer {
    return FfiConverterTypeSetupState.lower(value)
}





public protocol AppReconciler: AnyObject, Sendable {
    
    func reconcile(update: AppUpdate) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceAppReconciler {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceAppReconciler = UniffiVTableCallbackInterfaceAppReconciler(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceAppReconciler.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface AppReconciler: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceAppReconciler.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface AppReconciler: handle missing in uniffiClone")
            }
        },
        reconcile: { (
            uniffiHandle: UInt64,
            update: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceAppReconciler.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.reconcile(
                     update: try FfiConverterTypeAppUpdate_lift(update)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceAppReconciler> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceAppReconciler>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitAppReconciler() {
    uniffi_rebel_wallet_core_fn_init_callback_vtable_appreconciler(UniffiCallbackInterfaceAppReconciler.vtablePtr)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceAppReconciler {
    fileprivate static let handleMap = UniffiHandleMap<AppReconciler>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceAppReconciler : FfiConverter {
    typealias SwiftType = AppReconciler
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceAppReconciler_lift(_ handle: UInt64) throws -> AppReconciler {
    return try FfiConverterCallbackInterfaceAppReconciler.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceAppReconciler_lower(_ v: AppReconciler) -> UInt64 {
    return FfiConverterCallbackInterfaceAppReconciler.lower(v)
}




public protocol SecretStore: AnyObject, Sendable {
    
    func getSecret(key: String)  -> String?
    
    func setSecret(key: String, value: String)  -> Bool
    
    func deleteSecret(key: String)  -> Bool
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceSecretStore {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceSecretStore = UniffiVTableCallbackInterfaceSecretStore(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceSecretStore.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface SecretStore: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceSecretStore.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface SecretStore: handle missing in uniffiClone")
            }
        },
        getSecret: { (
            uniffiHandle: UInt64,
            key: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> String? in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceSecretStore.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.getSecret(
                     key: try FfiConverterString.lift(key)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterOptionString.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        setSecret: { (
            uniffiHandle: UInt64,
            key: RustBuffer,
            value: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<Int8>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Bool in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceSecretStore.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.setSecret(
                     key: try FfiConverterString.lift(key),
                     value: try FfiConverterString.lift(value)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterBool.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        deleteSecret: { (
            uniffiHandle: UInt64,
            key: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<Int8>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Bool in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceSecretStore.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.deleteSecret(
                     key: try FfiConverterString.lift(key)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterBool.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceSecretStore> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceSecretStore>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitSecretStore() {
    uniffi_rebel_wallet_core_fn_init_callback_vtable_secretstore(UniffiCallbackInterfaceSecretStore.vtablePtr)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceSecretStore {
    fileprivate static let handleMap = UniffiHandleMap<SecretStore>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceSecretStore : FfiConverter {
    typealias SwiftType = SecretStore
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceSecretStore_lift(_ handle: UInt64) throws -> SecretStore {
    return try FfiConverterCallbackInterfaceSecretStore.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceSecretStore_lower(_ v: SecretStore) -> UInt64 {
    return FfiConverterCallbackInterfaceSecretStore.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeActivityItem: FfiConverterRustBuffer {
    typealias SwiftType = [ActivityItem]

    public static func write(_ value: [ActivityItem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeActivityItem.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ActivityItem] {
        let len: Int32 = try readInt(&buf)
        var seq = [ActivityItem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeActivityItem.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeContact: FfiConverterRustBuffer {
    typealias SwiftType = [Contact]

    public static func write(_ value: [Contact], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeContact.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Contact] {
        let len: Int32 = try readInt(&buf)
        var seq = [Contact]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeContact.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeNostrMessage: FfiConverterRustBuffer {
    typealias SwiftType = [NostrMessage]

    public static func write(_ value: [NostrMessage], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeNostrMessage.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [NostrMessage] {
        let len: Int32 = try readInt(&buf)
        var seq = [NostrMessage]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeNostrMessage.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeScreen: FfiConverterRustBuffer {
    typealias SwiftType = [Screen]

    public static func write(_ value: [Screen], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeScreen.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Screen] {
        let len: Int32 = try readInt(&buf)
        var seq = [Screen]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeScreen.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_rebel_wallet_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_rebel_wallet_core_checksum_method_ffiapp_dispatch() != 30242) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rebel_wallet_core_checksum_method_ffiapp_listen_for_updates() != 17166) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rebel_wallet_core_checksum_method_ffiapp_state() != 63344) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rebel_wallet_core_checksum_constructor_ffiapp_new() != 52392) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rebel_wallet_core_checksum_method_appreconciler_reconcile() != 61199) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rebel_wallet_core_checksum_method_secretstore_get_secret() != 61340) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rebel_wallet_core_checksum_method_secretstore_set_secret() != 32351) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rebel_wallet_core_checksum_method_secretstore_delete_secret() != 38126) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitAppReconciler()
    uniffiCallbackInitSecretStore()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureRebelWalletCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all